### PR TITLE
Update PwnedPasswords.php

### PR DESCRIPTION
**Pull request by azjezz**

### CODE REVIEW

**Comment by azjezz** [comment]
added cache.
before , a simple script like this : 
```
$pw = new PwnedPasswords();
if($pw->isInsecure('123456')) {
   echo 'Ops, this password have been pwned ' . $pw->getCount('123456');
}
```
causes 2 curl request, now it only cause one, thanks to the cache.

**Comment by azjezz** [comment]
`PwnedPasswords::isInsecure()` now returns true if the password is pawned even once.
consider removing the `$maxUsage` options and keeping the method.

**Comment by azjezz** [comment]
throws `RuntimeException` if curl failed.

**Comment by azjezz** [comment]
keeping `isInsecure()` method.
removed `$maxUsage` option.

**Comment by azjezz** [comment]
- added fetch method ( curl or file ) 
example : 
```php
// uses file_get_contents if curl failed
$pp = new PwnedPassword();
// specify curl options 
$pp = new PwnedPassword(null,$curlOptions);
// use file_get_contents
$pp = new PwnedPassword(PwnedPassword::FILE);
// use curl 
$pp = new PwnedPassword(PwnedPassword::CURL);
// use curl with the given options
$pp = new PwnedPassword(PwnedPassword::CURL,$options);
```
- throws InvalidArgumentException if the given password is empty
- throws RuntimeException if connection to the API failed

**Comment by azjezz** [comment]
@ron-maxweb what do you think ?

**Comment by mxrxdxn** [comment]
This is great stuff! Merged in!

**Pull request merged**
